### ISSUE TITLE
Evaluate how deltalake release 0.20.1 changes the internal support for S3 

### ISSUE THREAD

**Issue by CGodiksen** [ModelarData/ModelarDB-RS#221]
`deltalake` release 0.20.1 will include changes to how they handle "S3-like" object stores such as MinIO. When updating to this release, we should look into how this changes our internal support for S3 and MinIO. A discussion on this was started here: https://github.com/ModelarData/ModelarDB-RS/pull/219#discussion_r1779022234.

**Comment by skejserjensen** [comment]
The changelog for `deltalake` 0.20.1 has now been [released](https://github.com/delta-io/delta-rs/commit/8f4232f8bd295db4c4498a2e4c3f2e35cf3e8581#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR10) and it does not look like [66441d1](https://github.com/delta-io/delta-rs/commit/66441d10ec54a8afb31f6b46489f15ef3369d8bd) is included.
