### ISSUE TITLE
Use a single connection for data and metadata management

### ISSUE THREAD

**Issue by skejserjensen** [ModelarData/ModelarDB-RS#227]
As management of [data](https://github.com/ModelarData/ModelarDB-RS/pull/185) and [metadata](https://github.com/ModelarData/ModelarDB-RS/pull/208) using [`deltalake`](https://crates.io/crates/deltalake) was developed in parallel, is code and configuration for connecting to, reading from, and writing to object stores of different types duplicated across the [`modelardb_common/src/storage.rs`](https://github.com/ModelarData/ModelarDB-RS/blob/main/crates/modelardb_common/src/storage.rs) and  [`modelardb_common/src/metadata`](https://github.com/ModelarData/ModelarDB-RS/tree/main/crates/modelardb_common/src/metadata) modules. This seems unnecessary and a single type for connecting to and performing operations on the object store in ModelarDB should be created.

**Comment by CGodiksen** [comment]
When combining these into a single type we should also reconsider whether we want to add unit tests for the `DeltaLake` struct directly or continue to rely on other components testing the functionality indirectly.
